-- Required Supabase vector store used by both index.js and streamlit_app.py.
-- sentence-transformers/all-MiniLM-L6-v2 creates 384-dimensional vectors.

create extension if not exists vector with schema extensions;

create table if not exists public.documents (
  -- Python supplies a stable bigint ID, so repeated serverless runs upsert.
  -- index.js may omit it and use this identity default instead.
  id bigint generated by default as identity primary key,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding extensions.vector(384) not null
);

create index if not exists documents_metadata_gin_idx
  on public.documents using gin (metadata);

alter table public.documents enable row level security;

-- LangChain calls this function during semantic search. The JSON filter keeps
-- results scoped to the current resume_id stored in each chunk's metadata.
create or replace function public.match_documents (
  query_embedding extensions.vector(384),
  match_count integer default 6,
  filter jsonb default '{}'::jsonb
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity double precision
)
language sql
stable
as $$
  select
    document.id,
    document.content,
    document.metadata,
    1 - (document.embedding <=> query_embedding) as similarity
  from public.documents as document
  where document.metadata @> filter
  order by document.embedding <=> query_embedding
  limit least(match_count, 20);
$$;

-- Keep this table private. Use a server-side Supabase secret/service-role key
-- in Streamlit secrets; never expose that key in browser-side code.
